version: "3"
services:
  web:
    build: web/
    ports:
      - "8080:8080"
    links:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: runetracker
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
