version: "3.6"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - database
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: runetracker
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
